services:
  - type: web
    name: presentation-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && python generate_token.py"
    startCommand: "gunicorn presentation_project.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 2"
    envVars:
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*.render.com"
      - key: GROQ_API_KEY
        value: "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"
